### PR TITLE
Add upcoming meetings to events.json

### PR DESCRIPTION
**Pull request by willyogo**

### CODE REVIEW

**Comment by zakangelle** [comment]
Hey @willyogo, we just updated our events data shape to include a new `type` field -- updated the integration docs [here](https://docs.boardroom.info/v/1.1.0/boardroom-portal-1/adding-your-project/protocol-information#events) if you wanna see how that looks now. 

It looks like you'll just have to add a new line with `type` to each event, e.g.:

```json
{
    "title": "Weekly Governance Call",
    "url": "https://discord.gg/shapeshift",
    "date": "2021-08-05T15:00:00-06:00",
    "type": "call"
}
```

Lemme know if you have any questions.

**Comment by willyogo** [comment]
thanks @zakangelle, just added the "type" field to each

**Comment by zakangelle** [comment]
@willyogo Awesome, almost there -- looks like you just need to add a comma after each `date` line.

**Comment by willyogo** [comment]
@zakangelle thank you!! commas added

**Review by zakangelle — APPROVED** [review]
Perfect! Merging now.

**Pull request merged**
